[package]
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
name = "chalk"
version = "0.1.0"

[dependencies]
docopt = "0.8.1"
ena = "0.4"
error-chain = "0.11.0"
itertools = "0.6.0"
lalrpop-intern = "0.13.1"
lazy_static = "0.2.2"
petgraph = "0.4.5"
rustyline = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dependencies.chalk-parse]
path = "chalk-parse"

[workspace]
